In [1]:
import numpy as np

In [4]:
names = np.array(['ahmed', 'mohammed', 'anas', 'foad', 'loay', 'gamal', 'saed'])
ids = np.array(['120215568', '120216874', '120219874', '120214532', '120212258', '120214521', '120217452'])
grades = np.array([[94,85,88], [75,89,91], [92,84,82], [74,78,81], [72,73,77], [64,82,78], [95,92,89]])
GPAs = np.array([89, 85, 86, 77, 74, 74, 92])

In [9]:
print(names[GPAs> 85])

['ahmed' 'anas' 'saed']


In [10]:
print(ids[GPAs> 85])

['120215568' '120219874' '120217452']


In [11]:
print(grades[GPAs> 85])

[[94 85 88]
 [92 84 82]
 [95 92 89]]


In [21]:
grades[GPAs> 90,2]=90
print(grades)

[[94 85 88]
 [75 89 91]
 [92 84 82]
 [74 78 81]
 [72 73 77]
 [64 82 78]
 [95 92 90]]


In [14]:
GPAs[GPAs> 90] = 100
print(GPAs)

[ 89  85  86  77  74  74 100]


In [19]:
#EX2
arr = np.arange(16).reshape((4, 4))
arr[[0,1,2,2,3],[0,1,1,2,0]]

array([ 0,  5,  9, 10, 12])

In [18]:
#Ex 3
arr = np.arange(30).reshape((2, 3, 5))
print(arr.transpose(2,1,0))

[[[ 0 15]
  [ 5 20]
  [10 25]]

 [[ 1 16]
  [ 6 21]
  [11 26]]

 [[ 2 17]
  [ 7 22]
  [12 27]]

 [[ 3 18]
  [ 8 23]
  [13 28]]

 [[ 4 19]
  [ 9 24]
  [14 29]]]


In [22]:
arr = np.random.randn(7) * 5
np.sqrt(arr, arr)

C:\Users\CHIP2022\AppData\Local\Temp\ipykernel_596\522832853.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([0.60033797, 0.89167895, 1.98719063, 2.47014135, 2.1825284 ,
              nan, 2.37868674])

In [23]:
arr

array([0.60033797, 0.89167895, 1.98719063, 2.47014135, 2.1825284 ,
              nan, 2.37868674])

In [28]:
points = np.arange(-5, 5, 0.01)
xs = np.meshgrid(points,points)

In [29]:
xs

[array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        ...,
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]]),
 array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
        [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
        [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
        ...,
        [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
        [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
        [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])]

In [30]:
arr = np.random.randn(5, 4)

In [31]:
arr

array([[-0.2534364 ,  1.56101669, -1.33224671, -2.22514618],
       [ 1.06204589,  0.13251412, -0.00959935, -0.91011458],
       [ 0.90410162, -0.83088634,  1.22300091,  0.37269437],
       [-0.00835699, -1.03950649,  0.4550946 ,  2.18281846],
       [ 0.55508003,  0.04200891,  1.06857501, -0.80985064]])

In [32]:
arr.mean()

0.10699034536676585

In [1]:
list1 = [1,2,3,4]

list2 = [2,4,5,6]

list3 = [2,6,7,8]

result = list()

result.extend(i for i in list1 if i not in (list2-list3) and i not in result)

result.extend(i for i in list2 if i not in (list1-list3) and i not in result)

result.extend(i for i in list3 if i not in (list1-list2) and i not in result)
result


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [4]:
b = [1,0,2,0,"gh",'',[]]
list(filter(bool,b))

[1, 2, 'gh']

In [7]:
i=[1, 0, 2, 0, 'hello', ", []]
    list(filter(bool, 1))

SyntaxError: EOL while scanning string literal (1254127295.py, line 1)

In [10]:
def f1(*args, **kwargs):

    print("Sanfoundry")

    return x(*args, **kwargs)



In [12]:
f1(1,2)

Sanfoundry


NameError: name 'x' is not defined

In [14]:
x = [[0], [1]]

print((''.join(list(map(str, x))),))

('[0][1]',)


In [18]:
for i in [1, 2, 3, 4][::-1]:

    print (i)

4
3
2
1


In [17]:
min(max(False, 3,-4), 2,7)

2