# Revision Exercises

In [1]:
import numpy as np

- Create a 3x3 NumPy array with random values between 0 and 1. Then,
calculate the **mean** and the **median** for each row then for each column
and print the result then print the value of the standard deviation .

In [3]:
arr1 = np.random.uniform(size = (3,3))
q = arr1.mean(0)
z = arr1.mean(1)
e = np.median(arr1, axis=1)
m = np.median(arr1, axis=0)
print(q,'\n')
print(z,'\n')
print(e,'\n')
print(m,'\n')
print(arr1.std())


[0.46072846 0.74820828 0.27238672] 

[0.53359615 0.69813629 0.24959103] 

[0.49452209 0.69391867 0.12397886] 

[0.49452209 0.69391867 0.15581739] 

0.3026559008027986


-  Create a NumPy array with the values [1, 2, 3, 4, 5]. Using slicing, extract
the values at the even indices and print the result .

In [7]:
arr3 = np.array([1, 2, 3, 4, 5])
print(arr3[::2])

[1 3 5]


- Create a 4x4 NumPy array with the values [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10,
11, 12], [13, 14, 15, 16]]. Using slicing, extract the subarray with the
values [[6, 7], [10, 11]] and print the result .

In [11]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10,11, 12], [13, 14, 15, 16]])
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

- Create a NumPy array with values ranging from 0 to 9 and extract the
even values in a new array and the primary numbers in a new array.

In [4]:
arr = np.arange(10)
c = arr[::2]
print(c)
prime = np.in1d(arr,[2,3,5,7])
print(arr[prime])

[0 2 4 6 8]
[2 3 5 7]


- Create a NumPy array with values ranging from 0 to 9 and reshape it to a
3x3 array. Then, slice the array to obtain a 2x2 array starting from the
second row and second column.

In [32]:
arrnow = np.arange(9).reshape(3,3)
arrnow[1:,1:]

array([[4, 5],
       [7, 8]])

- Create a NumPy array with values ranging from 0 to 9 and use Boolean
indexing to replace all odd values with -1.

In [18]:
arr1 = np.arange(10)
arr1[(arr1%2)!=0]=-1
print(arr1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


- Create a NumPy array with values ranging from 0 to 9 and use fancy
indexing to obtain a new array with the elements in reverse order.

In [20]:
arr3 = np.arange(10)
print(arr3[::-1])

[9 8 7 6 5 4 3 2 1 0]
