In [2]:
import numpy as np

In [3]:
# Q1 :
names = np.array(['ahmed', 'mohammed', 'anas', 'foad', 'loay', 'gamal', 'saed'])
ids = np.array(['120215568', '120216874', '120219874', '120214532', '120212258', '120214521', '120217452'])
grades = np.array([[94,85,88], [75,89,91], [92,84,82], [74,78,81], [72,73,77], [64,82,78], [95,92,89]])
GPAs = np.array([89, 85, 86, 77, 74, 74, 92])

In [4]:
names[GPAs>85]

array(['ahmed', 'anas', 'saed'], dtype='<U8')

In [5]:
ids[GPAs>85]

array(['120215568', '120219874', '120217452'], dtype='<U9')

In [6]:
grades[GPAs>85]

array([[94, 85, 88],
       [92, 84, 82],
       [95, 92, 89]])

In [7]:
grades[GPAs>90,2] = 90
grades

array([[94, 85, 88],
       [75, 89, 91],
       [92, 84, 82],
       [74, 78, 81],
       [72, 73, 77],
       [64, 82, 78],
       [95, 92, 90]])

In [8]:
grades[grades>90] = 100
grades

array([[100,  85,  88],
       [ 75,  89, 100],
       [100,  84,  82],
       [ 74,  78,  81],
       [ 72,  73,  77],
       [ 64,  82,  78],
       [100, 100,  90]])

In [9]:
# Q2 :
arr = np.arange(16).reshape((4, 4))
print(arr[[0,1,2,2,3],[0,1,1,2,0]])

[ 0  5  9 10 12]


In [10]:
# Q3 :
arr = np.arange(30).reshape((2, 3, 5))
print(arr.transpose(2,1,0))

[[[ 0 15]
  [ 5 20]
  [10 25]]

 [[ 1 16]
  [ 6 21]
  [11 26]]

 [[ 2 17]
  [ 7 22]
  [12 27]]

 [[ 3 18]
  [ 8 23]
  [13 28]]

 [[ 4 19]
  [ 9 24]
  [14 29]]]
