In [1]:
import numpy as np
arr = np.random.rand(10)*100

In [2]:
np.sqrt(arr, arr)
x,y = np.modf(arr)
print(y)

[9. 7. 6. 6. 6. 5. 7. 1. 2. 3.]


In [3]:
balance = np.array([1000,300,1200,400,180,650,70,4560])
balance[balance<500] = 0
balance

array([1000,    0, 1200,    0,    0,  650,    0, 4560])

In [4]:
values = np.arange(20).reshape((5,4))
values.cumsum(0)


array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36],
       [40, 45, 50, 55]], dtype=int32)

In [13]:
cumprod1=values.cumprod(1)
cumprod1

array([[    0,     0,     0,     0],
       [    4,    20,   120,   840],
       [    8,    72,   720,  7920],
       [   12,   156,  2184, 32760],
       [   16,   272,  4896, 93024]], dtype=int32)

In [14]:
np.max(cumprod1)

93024

In [15]:
np.min(cumprod1)

0

In [17]:
(cumprod1 > 1000).sum()

5

In [63]:
arr2 = np.random.rand(12).reshape(4,3)*100
arr2

array([[49.35741224,  1.61974045, 76.88710594],
       [50.19241442, 70.66342991, 20.47950788],
       [87.54310069, 15.06572852,  2.71119851],
       [50.28854376, 93.65378358, 83.90223239]])

In [65]:
arr2.sort(0)
arr2

array([[ 1.61974045, 15.06572852, 70.66342991],
       [ 2.71119851, 49.35741224, 76.88710594],
       [20.47950788, 50.19241442, 87.54310069],
       [50.28854376, 83.90223239, 93.65378358]])

In [66]:
np.save('array', arr2)


In [70]:
c = np.load('array.npy')
c @ arr2.T 

array([[ 5222.92006185,  6181.1034329 ,  6975.45253688,  7963.4002157 ],
       [ 6181.1034329 ,  8355.13180043,  9263.82735876, 11478.30767672],
       [ 6975.45253688,  9263.82735876, 10602.48318757, 13439.88285325],
       [ 7963.4002157 , 11478.30767672, 13439.88285325, 18339.55341182]])

In [75]:
arr3 = np.random.rand(12)*10
r , w = np.modf(arr3)
t = np.unique(w)
t

array([0., 2., 4., 5., 6., 7., 8.])

In [76]:
np.isin(t,[0,2,4,6,8])

array([ True,  True,  True, False,  True, False,  True])

In [78]:
(t%2).all()

False